# Generated by Django 3.0.5 on 2020-05-01 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='static/web/media')),
                ('resume', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2020, 5, 1, 21, 58, 44, 416979, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
