# Generated by Django 3.0.5 on 2020-05-01 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200501_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 22, 30, 56, 426494, tzinfo=utc)),
        ),
    ]
