# Generated by Django 3.0.5 on 2020-05-01 23:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200501_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 23, 21, 35, 709746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='./static/web/media/'),
        ),
    ]
