# Generated by Django 3.0.6 on 2020-05-05 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200505_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 20, 32, 43, 630183, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='static/web/media/'),
        ),
    ]
